# Generated by Django 3.0.5 on 2021-02-09 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20210209_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='organisation',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='leads.UserProfile'),
            preserve_default=False,
        ),
    ]
